# This is a basic workflow to help you get started with Actions

name: Build CoreELEC/VDR Matrix

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build CoreELEC-VDR
        run: |
          chmod +x build.sh
          ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: coreelec-vdr.tar.gz
          path: CoreELEC/build-artifacts/coreelec-vdr.tar.gz

# Not yet
#      - uses: actions/upload-artifact@v3
#        with:
#          name: CoreELEC-Amlogic-ng.arm-19.4-Matrix_VDR_devel.tar
#          path: CoreELEC/build-artifacts/CoreELEC-Amlogic-ng.arm-19.4-Matrix_VDR_devel.tar
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: CoreELEC-Amlogic-ng.arm-19.4-Matrix_VDR_devel-Odroid_C4.img.gz
#          path: CoreELEC/build-artifacts/CoreELEC-Amlogic-ng.arm-19.4-Matrix_VDR_devel-Odroid_C4.img.gz