# This is a basic workflow to help you get started with Actions

name: Build CoreELEC/VDR Matrix

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Checkout CoreELEC-VDR
        run: |
          if [ ! -d CoreELEC ]; then 
            git clone https://github.com/Zabrimus/CoreELEC.git 
            cd CoreELEC 
          else 
            cd CoreELEC 
            git pull 
          fi
          
          git checkout exp-vdr-opt 
