# This is a basic workflow to help you get started with Actions

name: Build CoreELEC/VDR Matrix

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build CoreELEC-VDR
        run: |
          chmod +x build.sh
          ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: coreelec-vdr.tar.gz
          path: CoreELEC/target/coreelec-vdr.tar.gz